# Generated by Django 5.2.17 on 2026-10-04 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("manual", "Manual (UPI / bank transfer)"),
                        ],
                        default="razorpay",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending_verification", "Awaiting manual verification"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=24,
                    ),
                ),
                (
                    "gateway_order_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("gateway_signature", models.CharField(blank=True, max_length=128)),
                (
                    "manual_reference",
                    models.CharField(
                        blank=True,
                        help_text="UPI transaction ID / bank reference.",
                        max_length=80,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("billed_name", models.CharField(max_length=160)),
                ("billed_email", models.EmailField(max_length=254)),
                ("billed_phone", models.CharField(blank=True, max_length=15)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(default="razorpay", max_length=20)),
                ("event_id", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=60)),
                ("payload", models.JSONField(default=dict)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("result", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-processed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gateway", "event_id"), name="unique_webhook_event"
                    )
                ],
            },
        ),
    ]
