# Generated by Django 5.2.17 on 2026-10-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_subscription_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Razorpay subscription this payment belongs to (auto-renewal).",
                max_length=64,
            ),
        ),
    ]
