# Generated by Django 5.2.17 on 2026-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_gateway_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("payu", "PayU"),
                    ("razorpay", "Razorpay"),
                    ("manual", "Manual (UPI / bank transfer)"),
                ],
                default="payu",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway_subscription_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Gateway mandate/subscription this payment belongs to (auto-renewal).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="gateway",
            field=models.CharField(default="payu", max_length=20),
        ),
    ]
