# Generated by Django 5.2.17 on 2026-10-04 04:39

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                (
                    "image",
                    models.ImageField(
                        upload_to="banners/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp"]
                            ),
                            core.validators.validate_image_file,
                        ],
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                ("link_url", models.URLField(blank=True)),
                ("cta_label", models.CharField(blank=True, max_length=40)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_top", "Homepage - below hero"),
                            ("home_middle", "Homepage - middle"),
                            ("search", "Search results sidebar"),
                        ],
                        db_index=True,
                        default="home_top",
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["placement", "display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=160)),
                ("message", models.TextField(max_length=3000)),
                ("is_resolved", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_featured", "Homepage featured row"),
                            ("search_top", "Top of search results"),
                        ],
                        default="search_top",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(default="Sponsored", max_length=40)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Internal notes (not shown publicly).",
                        max_length=255,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisements",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=80)),
                (
                    "target_type",
                    models.CharField(blank=True, db_index=True, max_length=60),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Bangarpet Property Hub", max_length=120),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Find. Rent. Buy. Manage.", max_length=160
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. When empty the built-in logo is used.",
                        upload_to="branding/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp"]
                            ),
                            core.validators.validate_image_file,
                        ],
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=20)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Public WhatsApp support number, e.g. +919876543210",
                        max_length=20,
                    ),
                ),
                ("office_address", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True, verbose_name="X / Twitter URL")),
                ("linkedin_url", models.URLField(blank=True)),
                ("default_state", models.CharField(default="Karnataka", max_length=60)),
                ("default_district", models.CharField(default="Kolar", max_length=60)),
                (
                    "default_map_lat",
                    models.DecimalField(
                        decimal_places=6, default=12.9911, max_digits=9
                    ),
                ),
                (
                    "default_map_lng",
                    models.DecimalField(
                        decimal_places=6, default=78.1774, max_digits=9
                    ),
                ),
                (
                    "listing_policy",
                    models.TextField(
                        default="Only list properties you own or are authorised to market.\nProvide accurate prices, photos and details. Do not post duplicate listings.\nPhotos must be of the actual property and must not contain contact details or watermarks of other platforms.\nListings are reviewed before publishing and may be removed if they violate these rules."
                    ),
                ),
                ("require_listing_approval", models.BooleanField(default=True)),
                ("expiry_reminder_days", models.PositiveSmallIntegerField(default=5)),
                (
                    "allow_manual_payments",
                    models.BooleanField(
                        default=False,
                        help_text="Allow partners to submit UPI/bank transfer references for manual verification.",
                    ),
                ),
                ("manual_payment_instructions", models.TextField(blank=True)),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        help_text="Shown on invoices when set.",
                        max_length=20,
                        verbose_name="GSTIN",
                    ),
                ),
                ("invoice_business_name", models.CharField(blank=True, max_length=160)),
                ("email_notifications_enabled", models.BooleanField(default=True)),
                ("whatsapp_notifications_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_town",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "town"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="properties.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "platform settings",
                "verbose_name_plural": "platform settings",
            },
        ),
    ]
