# Generated by Django 5.2.17 on 2026-10-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_stored_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsetting",
            name="contact_limit_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Customers see a limited number of owner phone numbers each month, then need the Contact Pass.",
                verbose_name="Limit free owner contacts",
            ),
        ),
        migrations.AddField(
            model_name="platformsetting",
            name="free_contacts_per_month",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Owner contacts a customer can unlock for free each month.",
            ),
        ),
    ]
