# Generated by Django 5.2.17 on 2026-10-07 16:38

import django.core.validators
from django.db import migrations, models


def turn_on_upi(apps, schema_editor):
    """Switch on UPI / bank transfer payments for the existing site settings row."""
    apps.get_model("core", "PlatformSetting").objects.filter(pk=1).update(allow_manual_payments=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contact_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsetting",
            name="upi_id",
            field=models.CharField(
                blank=True,
                help_text="Shown with a QR code and a pay-by-UPI-app link on the payment page, e.g. bangarpetproperty@okhdfcbank.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9.\\-_]{2,256}@[A-Za-z][A-Za-z0-9]{1,63}$",
                        "Enter a UPI ID like name@okhdfcbank.",
                    )
                ],
                verbose_name="UPI ID",
            ),
        ),
        migrations.AddField(
            model_name="platformsetting",
            name="upi_payee_name",
            field=models.CharField(
                blank=True,
                help_text="The name UPI apps show when paying, e.g. Bangarpet Property Hub.",
                max_length=60,
                verbose_name="UPI payee name",
            ),
        ),
        migrations.AlterField(
            model_name="platformsetting",
            name="allow_manual_payments",
            field=models.BooleanField(
                default=True,
                help_text="Owners, brokers and Contact Pass buyers can pay to your UPI ID and submit the UPI reference; the plan activates when you approve it in Payments.",
                verbose_name="Allow UPI / bank transfer payments",
            ),
        ),
        migrations.AlterField(
            model_name="platformsetting",
            name="manual_payment_instructions",
            field=models.TextField(
                blank=True,
                help_text="Optional extra steps, e.g. bank account details for NEFT/IMPS.",
            ),
        ),
        migrations.RunPython(turn_on_upi, migrations.RunPython.noop),
    ]
