# Generated by Django 5.2.17 on 2026-10-08 03:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_upi_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                (
                    "youtube_url",
                    models.URLField(
                        help_text="Any YouTube video or Shorts link.",
                        validators=[core.models.validate_youtube_url],
                        verbose_name="YouTube link",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "show_on_home",
                    models.BooleanField(default=True, verbose_name="Show on homepage"),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
