# Generated by Django 5.2.17 on 2026-10-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_youtube_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformsetting",
            name="require_listing_approval",
        ),
    ]
