# Generated by Django 5.2.17 on 2026-10-09 09:46

import accounts.models
import adminpanel.models
import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spent_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="Date",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("office", "Office rent & maintenance"),
                            ("salaries", "Salaries & staff"),
                            ("marketing", "Marketing & ads"),
                            ("software", "Website, software & hosting"),
                            ("phone", "Phone & internet"),
                            ("travel", "Travel & fuel"),
                            ("commission", "Commission paid"),
                            ("printing", "Printing & stationery"),
                            ("utilities", "Electricity & utilities"),
                            ("taxes", "Taxes, GST & fees"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=160, verbose_name="What for"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Amount (₹)",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("cash", "Cash"),
                            ("bank", "Bank transfer"),
                            ("card", "Card"),
                            ("cheque", "Cheque"),
                        ],
                        default="upi",
                        max_length=10,
                        verbose_name="Paid by",
                    ),
                ),
                ("paid_to", models.CharField(blank=True, max_length=120)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Bill / UPI reference"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        help_text="Optional. PDF or photo; only Management can open it.",
                        storage=accounts.models.private_storage,
                        upload_to=adminpanel.models.receipt_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            ),
                            core.validators.validate_document_file,
                        ],
                        verbose_name="Bill / receipt photo",
                    ),
                ),
                (
                    "receipt_name",
                    models.CharField(blank=True, editable=False, max_length=160),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-spent_on", "-created_at"],
            },
        ),
    ]
