# Generated by Django 5.2.17 on 2026-10-04 04:39

import accounts.models
import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=15,
                        validators=[core.validators.validate_indian_phone],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer / Tenant / Buyer"),
                            ("owner", "Property owner"),
                            ("broker", "Real estate broker"),
                            ("admin", "Super admin"),
                        ],
                        db_index=True,
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.CharField(blank=True, max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BrokerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not submitted"),
                            ("pending", "Pending review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                (
                    "verification_note",
                    models.CharField(
                        blank=True,
                        help_text="Reason shown to the partner.",
                        max_length=255,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("agency_name", models.CharField(max_length=160)),
                (
                    "business_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[core.validators.validate_indian_phone],
                    ),
                ),
                ("business_email", models.EmailField(blank=True, max_length=254)),
                ("office_address", models.TextField(blank=True)),
                (
                    "rera_number",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="RERA registration number",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not submitted"),
                            ("pending", "Pending review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                (
                    "verification_note",
                    models.CharField(
                        blank=True,
                        help_text="Reason shown to the partner.",
                        max_length=255,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        upload_to=accounts.models.avatar_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            core.validators.validate_image_file,
                        ],
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[core.validators.validate_indian_phone],
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="Bangarpet", max_length=80),
                ),
                ("about", models.TextField(blank=True, max_length=1000)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone", "Phone call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="phone",
                        max_length=10,
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(
                        default=True, verbose_name="Email notifications"
                    ),
                ),
                (
                    "notify_whatsapp",
                    models.BooleanField(
                        default=False, verbose_name="WhatsApp notifications"
                    ),
                ),
                (
                    "notify_marketing",
                    models.BooleanField(
                        default=False, verbose_name="Product updates and offers"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("aadhaar", "Aadhaar card (mask the first 8 digits)"),
                            ("pan", "PAN card"),
                            ("voter_id", "Voter ID"),
                            ("passport", "Passport"),
                            ("driving_licence", "Driving licence"),
                            (
                                "ownership",
                                "Ownership proof (tax receipt, sale deed extract, khata)",
                            ),
                            ("authorization", "Authorisation letter from owner"),
                            ("business", "Business registration / GST / trade licence"),
                            ("rera", "RERA registration certificate"),
                            ("other", "Other supporting document"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=accounts.models.private_storage,
                        upload_to=accounts.models.document_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            ),
                            core.validators.validate_document_file,
                        ],
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=255)),
                (
                    "retain_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="The file is purged after this date by the purge_verification_documents command.",
                        null=True,
                    ),
                ),
                ("file_purged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
