# Generated by Django 5.2.17 on 2026-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Management areas a staff member may use (see accounts.staff.AREAS).",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer / Tenant / Buyer"),
                    ("owner", "Property owner"),
                    ("broker", "Real estate broker"),
                    ("staff", "Staff member"),
                    ("admin", "Super admin"),
                ],
                db_index=True,
                default="customer",
                max_length=20,
            ),
        ),
    ]
