# Generated by Django 5.2.17 on 2026-10-04 04:39

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("icon", models.CharField(default="check2-circle", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "amenities",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="house",
                        help_text="Bootstrap Icons name, e.g. 'house-door'.",
                        max_length=40,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("allows_rent", models.BooleanField(default=True)),
                ("allows_sale", models.BooleanField(default=True)),
                (
                    "has_rooms",
                    models.BooleanField(
                        default=True,
                        help_text="Bedrooms/bathrooms are relevant for this category.",
                    ),
                ),
                ("is_commercial", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("town", "Town / city"), ("area", "Area / locality")],
                        db_index=True,
                        default="area",
                        max_length=10,
                    ),
                ),
                ("district", models.CharField(default="Kolar", max_length=60)),
                ("state", models.CharField(default="Karnataka", max_length=60)),
                (
                    "pin_code",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        validators=[core.validators.validate_pin_code],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Show in 'Popular areas' on the homepage.",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Town this area belongs to.",
                        limit_choices_to={"kind": "town"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="areas",
                        to="properties.location",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        editable=False, max_length=20, null=True, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("rent", "For rent"), ("sale", "For sale")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(max_length=5000)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("immediate", "Ready to move / immediately"),
                            ("from_date", "Available from a date"),
                            ("under_construction", "Under construction"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                ("state", models.CharField(default="Karnataka", max_length=60)),
                ("district", models.CharField(default="Kolar", max_length=60)),
                (
                    "locality",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Locality / landmark"
                    ),
                ),
                ("street_address", models.CharField(blank=True, max_length=255)),
                (
                    "pin_code",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        validators=[core.validators.validate_pin_code],
                        verbose_name="PIN code",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "show_exact_address",
                    models.BooleanField(
                        default=False,
                        help_text="When off, only the area and town are shown publicly and the map pin is approximate.",
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "bathrooms",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "balconies",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "built_up_area",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Built-up area (sq. ft)"
                    ),
                ),
                (
                    "land_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "land_area_unit",
                    models.CharField(
                        choices=[
                            ("sqft", "sq. ft"),
                            ("sqyd", "sq. yd"),
                            ("acre", "acre"),
                            ("gunta", "gunta"),
                        ],
                        default="sqft",
                        max_length=10,
                    ),
                ),
                (
                    "furnishing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unfurnished", "Unfurnished"),
                            ("semi", "Semi-furnished"),
                            ("fully", "Fully furnished"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "parking",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No parking"),
                            ("bike", "Two-wheeler"),
                            ("car", "Car"),
                            ("both", "Car and two-wheeler"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "floor_number",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "total_floors",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "property_age_years",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(150)],
                        verbose_name="Property age (years)",
                    ),
                ),
                (
                    "monthly_rent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maintenance_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Monthly maintenance",
                    ),
                ),
                ("is_negotiable", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube link to a walkthrough video.",
                        verbose_name="Video tour URL",
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[core.validators.validate_indian_phone],
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[core.validators.validate_indian_phone],
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone", "Phone call"),
                            ("whatsapp", "WhatsApp"),
                            ("enquiry", "Website enquiry"),
                        ],
                        default="phone",
                        max_length=10,
                    ),
                ),
                (
                    "contact_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Show phone to everyone"),
                            ("registered", "Show phone to signed-in users only"),
                            ("hidden", "Hide phone - enquiries only"),
                        ],
                        default="registered",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending approval"),
                            ("changes_requested", "Changes requested"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("rented", "Rented out"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                            ("removed", "Removed by admin"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("wizard_step", models.PositiveSmallIntegerField(default=1)),
                ("policy_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "expiry_reminder_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "moderation_note",
                    models.TextField(
                        blank=True, help_text="Latest reason shown to the owner."
                    ),
                ),
                ("is_suspicious", models.BooleanField(db_index=True, default=False)),
                (
                    "featured_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Visibility boost from the owner's plan."
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False,
                        help_text="Sample data created by the seed_demo command.",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("enquiry_count", models.PositiveIntegerField(default=0)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="properties", to="properties.amenity"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "area"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="area_properties",
                        to="properties.location",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="properties.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        limit_choices_to={"kind": "town"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="town_properties",
                        to="properties.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourited_by",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyDailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        upload_to=properties.models.property_image_upload_to,
                        width_field="width",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to=properties.models.property_image_upload_to
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=120)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                ("requires_moderation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentlyViewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recently_viewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("query_string", models.CharField(max_length=1000)),
                (
                    "notify",
                    models.BooleanField(
                        default=False,
                        help_text="Notify me about new matching listings.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "town"), ("parent__isnull", True)),
                    models.Q(("kind", "area"), ("parent__isnull", False)),
                    _connector="OR",
                ),
                name="location_kind_parent_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["status", "purpose", "category"], name="prop_status_purpose_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["status", "town", "area"], name="prop_status_location"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["status", "price"], name="prop_status_price"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["owner", "status"], name="prop_owner_status"),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("monthly_rent__isnull", True),
                    ("monthly_rent__gte", 0),
                    _connector="OR",
                ),
                name="prop_rent_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sale_price__isnull", True),
                    ("sale_price__gte", 0),
                    _connector="OR",
                ),
                name="prop_sale_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.UniqueConstraint(
                fields=("user", "property"), name="unique_favourite"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertydailystat",
            constraint=models.UniqueConstraint(
                fields=("property", "date"), name="unique_property_daily_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("property",),
                name="one_primary_image_per_property",
            ),
        ),
        migrations.AddConstraint(
            model_name="recentlyviewed",
            constraint=models.UniqueConstraint(
                fields=("user", "property"), name="unique_recently_viewed"
            ),
        ),
    ]
