# Generated by Django 5.2.17 on 2026-10-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_reference_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
