# Generated by Django 5.2.17 on 2026-10-09 09:56

from django.db import migrations, models


def public_to_registered(apps, schema_editor):
    """The "show phone to everyone" option is removed: those listings now show it to signed-in users."""
    apps.get_model("properties", "Property").objects.filter(contact_visibility="registered").update(contact_visibility="registered")


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_contact_unlock"),
    ]

    operations = [
        migrations.RunPython(public_to_registered, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="property",
            name="contact_visibility",
            field=models.CharField(
                choices=[
                    ("registered", "Show phone to signed-in users only"),
                    ("hidden", "Hide phone - enquiries only"),
                ],
                default="registered",
                max_length=12,
            ),
        ),
    ]
