# Generated by Django 5.2.17 on 2026-10-04 04:39

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField(max_length=2000)),
                ("contact_name", models.CharField(max_length=120)),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=15,
                        validators=[core.validators.validate_indian_phone],
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone", "Phone call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="phone",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("visit_requested", "Visit requested"),
                            ("visit_scheduled", "Visit scheduled"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "partner_note",
                    models.TextField(
                        blank=True,
                        help_text="Private note visible only to the owner/broker.",
                        max_length=2000,
                    ),
                ),
                ("last_status_change_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Owner or broker who manages the property at the time of the enquiry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnquiryStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="enquiries.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("preferred_date", models.DateField()),
                (
                    "preferred_slot",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (9 am - 12 pm)"),
                            ("afternoon", "Afternoon (12 pm - 4 pm)"),
                            ("evening", "Evening (4 pm - 7 pm)"),
                        ],
                        default="morning",
                        max_length=10,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("customer_note", models.CharField(blank=True, max_length=500)),
                (
                    "partner_note",
                    models.CharField(
                        blank=True,
                        help_text="Shared with the customer (e.g. meeting point).",
                        max_length=500,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="enquiries.enquiry",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(fields=["partner", "status"], name="enq_partner_status"),
        ),
        migrations.AddConstraint(
            model_name="enquiry",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["new", "contacted", "visit_requested", "visit_scheduled"],
                    )
                ),
                fields=("customer", "property"),
                name="one_open_enquiry_per_customer_property",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyvisit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["requested", "scheduled"])),
                fields=("customer", "property"),
                name="one_active_visit_per_customer_property",
            ),
        ),
    ]
