# Generated by Django 5.2.17 on 2026-10-04 04:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price (INR)",
                    ),
                ),
                (
                    "billing_period_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "listing_limit",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Maximum active listings at a time."
                    ),
                ),
                (
                    "listing_duration_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="How long an approved listing stays live.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("has_performance_stats", models.BooleanField(default=False)),
                ("has_priority_visibility", models.BooleanField(default=False)),
                ("has_advanced_enquiry_tools", models.BooleanField(default=False)),
                (
                    "visibility_priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Higher numbers rank earlier in default sorting.",
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="One feature per line, shown on the pricing page.",
                    ),
                ),
                (
                    "for_roles",
                    models.CharField(
                        default="owner,broker",
                        help_text="Comma separated roles allowed to buy this plan (owner,broker).",
                        max_length=20,
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(90)],
                    ),
                ),
                ("discount_label", models.CharField(blank=True, max_length=60)),
                ("discount_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Plan applied to partners without a paid subscription.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "price"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="single_default_plan",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("superseded", "Replaced by another plan"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expiry_reminder_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who granted this subscription manually, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "ends_at"], name="sub_user_status_end"
                    )
                ],
            },
        ),
    ]
