# Generated by Django 5.2.17 on 2026-10-06 07:19

from django.db import migrations, models


def add_contact_pass(apps, schema_editor):
    """Customer plan: unlimited owner contacts for 99 INR a month (editable in /management/)."""
    Plan = apps.get_model("subscriptions", "SubscriptionPlan")
    Plan.objects.get_or_create(slug="contact-pass", defaults=dict(
        name="Contact Pass", price=99, billing_period_days=30, listing_limit=0, listing_duration_days=30,
        for_roles="customer", unlimited_contacts=True, display_order=10,
        description="Unlimited owner phone and WhatsApp contacts.",
        features="Unlimited owner phone & WhatsApp contacts\nRenews automatically every month\nCancel anytime",
    ))


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_default_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="gateway_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Razorpay subscription (auto-renewal) ID.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="razorpay_plan_id",
            field=models.CharField(
                blank=True,
                help_text="Set automatically when the plan is first sold with auto-renewal.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="unlimited_contacts",
            field=models.BooleanField(
                default=False,
                help_text="Customer plan: unlimited owner phone/WhatsApp contacts (the Contact Pass).",
            ),
        ),
        migrations.RunPython(add_contact_pass, migrations.RunPython.noop),
    ]
