# Generated by Django 5.2.17 on 2026-10-07 09:39

from django.db import migrations, models

OLD_FEATURES = "Unlimited owner phone & WhatsApp contacts\nRenews automatically every month\nCancel anytime"
NEW_FEATURES = "Unlimited owner phone & WhatsApp contacts\nValid for 30 days\nPay by UPI, card or net banking"


def update_contact_pass_text(apps, schema_editor):
    """The pass is now a one-time purchase through PayU (only touches the untouched default text)."""
    Plan = apps.get_model("subscriptions", "SubscriptionPlan")
    Plan.objects.filter(slug="contact-pass", features=OLD_FEATURES).update(features=NEW_FEATURES)


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_contact_pass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="razorpay_plan_id",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="gateway_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Payment gateway mandate/subscription ID (auto-renewal).",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(update_contact_pass_text, migrations.RunPython.noop),
    ]
