# Generated by Django 5.2.17 on 2026-10-04 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("new_enquiry", "New customer enquiry"),
                            ("visit_request", "New property visit request"),
                            ("visit_confirmed", "Visit confirmation"),
                            ("visit_cancelled", "Visit cancelled"),
                            ("enquiry_update", "Enquiry status update"),
                            ("listing_approved", "Listing approved"),
                            ("listing_rejected", "Listing rejected"),
                            ("listing_changes", "Listing changes requested"),
                            ("listing_removed", "Listing removed"),
                            ("listing_expiring", "Listing expiry reminder"),
                            ("listing_expired", "Listing expired"),
                            ("subscription_purchased", "Subscription purchase"),
                            ("payment_confirmed", "Payment confirmation"),
                            ("payment_failed", "Payment failed"),
                            ("subscription_expiring", "Subscription expiry reminder"),
                            ("subscription_expired", "Subscription expired"),
                            ("verification_update", "Verification status update"),
                            ("account_notice", "Account notice"),
                            ("admin_notice", "Important notice"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(max_length=2000)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("not_configured", "Skipped - integration not configured"),
                            ("skipped", "Skipped - disabled or no recipient"),
                        ],
                        max_length=16,
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=160)),
                ("provider_message_id", models.CharField(blank=True, max_length=120)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
